services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5678:5672
      - 15678:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes: 
      - ./_data/rabbitmq:/var/lib/rabbitmq
    # tmpfs:
    #   - /var/lib/rabbitmq
    mem_limit: 500m
    mem_reservation: 300m
  # postgres:
  #   image: postgres:15.1-alpine
  #   ports:
  #     - 5438:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   # Required config for logical replication
  #   command: [ "postgres", "-c", "wal_level=logical" ]
  #   volumes:
  #     - ./_data/postgres:/var/lib/postgresql/data
  #   # tmpfs:
  #   #   - /var/lib/postgresql/data
  #   mem_limit: 500m
  #   mem_reservation: 300m
  # postgres:
  #   image: debezium/postgres:15-alpine
  #   ports:
  #     - 5438:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   volumes:
  #     - ./_data/postgres:/var/lib/postgresql/data
  #   # tmpfs:
  #   #   - /var/lib/postgresql/data
  #   mem_limit: 500m
  #   mem_reservation: 300m
  postgres:
    build:
      context: ./_conf/postgres
      dockerfile: Dockerfile
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    # tmpfs:
    #   - /var/lib/postgresql/data
    mem_limit: 500m
    mem_reservation: 300m
  adminer:
    image: adminer
    ports:
      - 8088:8080
    environment:
      ADMINER_DESIGN: hever
      ADMINER_DEFAULT_SERVER: postgres
    mem_limit: 500m
    mem_reservation: 300m
